
import Song from './Song'

export const SongList:Array<Song>=[

  new Song(1,"天外来物(Live)","薛之谦","https://www.shiyinren.com/server/1/160897073.mp3","https://img4.kuwo.cn/star/starheads/240/35/10/30088435.jpg"),
  new Song(2,"奢香夫人","凤凰传奇","http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/3.m4a","http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/3.jpg"),
  new Song(3,"离别开出花","就是南方凯","http://music.163.com/song/media/outer/url?id=2061978961.mp3","http://p1.music.126.net/MgrERz_auwIi5Km64TxwjQ==/109951169154658797.jpg?param=300x300"),
  new Song(4,"离别开出花","就是南方凯","http://music.163.com/song/media/outer/url?id=2061978961.mp3","http://p1.music.126.net/MgrERz_auwIi5Km64TxwjQ==/109951169154658797.jpg?param=300x300"),
  new Song(5,"离别开出花","就是南方凯","http://music.163.com/song/media/outer/url?id=2061978961.mp3","http://p1.music.126.net/MgrERz_auwIi5Km64TxwjQ==/109951169154658797.jpg?param=300x300"),
  new Song(6,"离别开出花","就是南方凯","http://music.163.com/song/media/outer/url?id=2061978961.mp3","http://p1.music.126.net/MgrERz_auwIi5Km64TxwjQ==/109951169154658797.jpg?param=300x300"),
  new Song(7,"离别开出花","就是南方凯","http://music.163.com/song/media/outer/url?id=2061978961.mp3","http://p1.music.126.net/MgrERz_auwIi5Km64TxwjQ==/109951169154658797.jpg?param=300x300"),
  new Song(8,"离别开出花","就是南方凯","http://music.163.com/song/media/outer/url?id=2061978961.mp3","http://p1.music.126.net/MgrERz_auwIi5Km64TxwjQ==/109951169154658797.jpg?param=300x300"),
  new Song(9,"离别开出花","就是南方凯","http://music.163.com/song/media/outer/url?id=2061978961.mp3","http://p1.music.126.net/MgrERz_auwIi5Km64TxwjQ==/109951169154658797.jpg?param=300x300"),
  new Song(10,"离别开出花","就是南方凯","http://music.163.com/song/media/outer/url?id=2061978961.mp3","http://p1.music.126.net/MgrERz_auwIi5Km64TxwjQ==/109951169154658797.jpg?param=300x300"),

]