
import Song from './Song'

export const SongList:Array<Song>=[

  new Song(1,"天外来物(Live)","薛之谦","https://www.shiyinren.com/server/1/160897073.mp3","https://img4.kuwo.cn/star/starheads/240/35/10/30088435.jpg"),
  new Song(2,"奢香夫人","凤凰传奇","http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/3.m4a","http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/3.jpg"),
  new Song(3,"佛系少女","冯提莫","http://music.163.com/song/media/outer/url?id=1869701934.mp3","http://p2.music.126.net/fzLb8mIeHLcDINhXlPJ0kA==/109951166286043013.jpg?param=300x300"),
  new Song(4,"做自己的光","DJ舒心","http://music.163.com/song/media/outer/url?id=2156636591.mp3","https://img1.kuwo.cn/star/albumcover/240/s3s42/65/2784609704.jpg"),
  new Song(5,"一笑倾城","就是南方凯","http://music.163.com/song/media/outer/url?id=1869972634.mp3","http://p1.music.126.net/XtQbs_V1OAvtZo9tmJFAJA==/1369991503018202.jpg?param=300x300"),
  new Song(6,"离别开出花","就是南方凯","http://music.163.com/song/media/outer/url?id=2127329045.mp3","http://p1.music.126.net/MgrERz_auwIi5Km64TxwjQ==/109951169154658797.jpg?param=300x300"),
  new Song(7,"Everywhere We Go","陈冠希","http://music.163.com/song/media/outer/url?id=65739.mp3","https://img2.kuwo.cn/star/starheads/240/64/17/3370271515.jpg"),
  new Song(8,"植物大战僵尸","王文照","http://music.163.com/song/media/outer/url?id=1387591467.mp3","https://star.kuwo.cn/star/starheads/180/79/78/2507339289.jpg"),
  new Song(9,"琵琶行","奇然","http://music.163.com/song/media/outer/url?id=476513774.mp3","http://p2.music.126.net/y1ZIkrc8mAPuH6uo7mYWyg==/109951168534927670.jpg?param=300x300"),
  new Song(10,"Trouble Maker","封茗囧菌","http://music.163.com/song/media/outer/url?id=1366724720.mp3","http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/4.jpg"),
  new Song(11,"我期待的一直都不是雪","DJ婷婷","http://music.163.com/song/media/outer/url?id=2158892173.mp3","http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/11.jpg"),
  new Song(12,"5.20AM","刀酱","http://music.163.com/song/media/outer/url?id=2124731026.mp3","http://p1.music.126.net/RjiI9yP2Fnxx5cxiTVCIrQ==/109951169318905148.jpg?param=300x300"),
  new Song(13,"未必","言瑾羽","http://music.163.com/song/media/outer/url?id=2133221972.mp3","http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/12.jpg"),

]